Trial and error

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,63 +1,172 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir> <env-dir>
 
-# fail fast
-set -e
+### Configure environment
 
-BP_DIR=$(cd $(dirname $0)/..; pwd) # absolute path
-BIN_DIR=$BP_DIR/bin
-OPT_DIR=$BP_DIR/opt
-LIB_DIR=$BP_DIR/lib
-. $LIB_DIR/common.sh
+set -o errexit    # always exit on error
+set -o pipefail   # don't ignore exit codes when piping output
+set -o nounset    # fail on unset variables
+unset GIT_DIR     # Avoid GIT_DIR leak from previous build steps
 
-# parse args
-BUILD_DIR=$1
-CACHE_DIR=$2
-ENV_DIR=$3
+### Constants
 
+DEFAULT_CACHE="node_modules bower_components"
+
+### Configure directories
+
+BUILD_DIR=${1:-}
+CACHE_DIR=${2:-}
+ENV_DIR=${3:-}
+BP_DIR=$(cd $(dirname ${0:-}); cd ..; pwd)
 GRADLE_TASK=${GRADLE_TASK-stage}
 
-print_env
-
-vendored_node_version=6.6.0
-node_dir=$CACHE_DIR/node
-bower_app=$node_dir/lib/node_modules/bower
-gulp_app=$node_dir/lib/node_modules/gulp
-
-if [ ! -d $node_dir ]; then
-    status "Vendoring Node v$vendored_node_version to run Bower."
-    mkdir -p $node_dir
-    curl -s http://s3pository.heroku.com/node/v$vendored_node_version/node-v$vendored_node_version-linux-x64.tar.gz | tar xfz - -C $node_dir --strip-components=1
-fi
-
-$node_dir/bin/npm -v
-$node_dir/bin/node -v
-
-if [ ! -d $bower_app ]; then
-    status  "Installing bower"
-    $node_dir/bin/npm --silent -g install bower
-fi
-
-status "installed bower"
-
-export bower_run=$node_dir/bin/bower
-PATH=$PATH:$node_dir/bin
-  
+mkdir -p "$BUILD_DIR/.heroku/node/"
 cd $BUILD_DIR
-status "Running: $bower_run --allow-root install"
-$bower_run --allow-root install
+export PATH="$BUILD_DIR/.heroku/node/bin":$PATH
 
-status  "Installing npm dependencies"
-$node_dir/bin/npm --silent install
+LOG_FILE='/tmp/node-build-log.txt'
+echo "" > "$LOG_FILE"
 
-if [ -e gulpfile.js ]; then
+### Load dependencies
 
-  export gulp_run=$BUILD_DIR/node_modules/.bin/gulp
+source $BP_DIR/lib/output.sh
+source $BP_DIR/lib/json.sh
+source $BP_DIR/lib/failure.sh
+source $BP_DIR/lib/environment.sh
+source $BP_DIR/lib/binaries.sh
+source $BP_DIR/lib/cache.sh
+source $BP_DIR/lib/dependencies.sh
 
-  status "Running: $gulp_run"
-  $gulp_run --env=prod
+### Handle errors
 
-fi
+handle_failure() {
+  header "Build failed"
+  warn_untracked_dependencies "$LOG_FILE"
+  warn_angular_resolution "$LOG_FILE"
+  warn_missing_devdeps "$LOG_FILE"
+  warn_econnreset "$LOG_FILE"
+  failure_message | output "$LOG_FILE"
+}
+trap 'handle_failure' ERR
+
+### Check initial state
+
+[ -e "$BUILD_DIR/node_modules" ] && PREBUILD=true || PREBUILD=false
+
+### Failures that should be caught immediately
+
+fail_invalid_package_json "$BUILD_DIR"
+warn_prebuilt_modules "$BUILD_DIR"
+warn_missing_package_json "$BUILD_DIR"
+
+### Compile
+
+create_env() {
+  write_profile "$BP_DIR" "$BUILD_DIR"
+  write_export "$BP_DIR" "$BUILD_DIR"
+  export_env_dir "$ENV_DIR"
+  create_default_env
+}
+
+header "Creating runtime environment"
+create_env # can't pipe the whole thing because piping causes subshells, preventing exports
+list_node_config | output "$LOG_FILE"
+
+install_bins() {
+  local node_engine=$(read_json "$BUILD_DIR/package.json" ".engines.node")
+  local iojs_engine=$(read_json "$BUILD_DIR/package.json" ".engines.iojs")
+  local npm_engine=$(read_json "$BUILD_DIR/package.json" ".engines.npm")
+
+  if [ -n "$iojs_engine" ]; then
+    echo "engines.iojs (package.json):  $iojs_engine (iojs)"
+  else
+    echo "engines.node (package.json):  ${node_engine:-unspecified}"
+  fi
+  echo "engines.npm (package.json):   ${npm_engine:-unspecified (use default)}"
+  echo ""
+
+  if [ -n "$iojs_engine" ]; then
+    warn_node_engine "$iojs_engine"
+    install_iojs "$iojs_engine" "$BUILD_DIR/.heroku/node"
+    echo "Using bundled npm version for iojs compatibility: `npm --version`"
+  else
+    warn_node_engine "$node_engine"
+    install_nodejs "$node_engine" "$BUILD_DIR/.heroku/node"
+    install_npm "$npm_engine" "$BUILD_DIR/.heroku/node"
+  fi
+  warn_old_npm
+}
+
+header "Installing binaries"
+install_bins | output "$LOG_FILE"
+
+restore_cache() {
+  local cache_status="$(get_cache_status)"
+
+  if [ "$cache_status" == "valid" ]; then
+    local cache_directories=$(get_cache_directories)
+    if [ "$cache_directories" == "" ]; then
+      echo "Loading 2 from cacheDirectories (default):"
+      restore_cache_directories "$BUILD_DIR" "$CACHE_DIR" "$DEFAULT_CACHE"
+    else
+      echo "Loading $(echo $cache_directories | wc -w | xargs) from cacheDirectories (package.json):"
+      restore_cache_directories "$BUILD_DIR" "$CACHE_DIR" $cache_directories
+    fi
+  else
+    echo "Skipping cache restore ($cache_status)"
+  fi
+}
+
+header "Restoring cache"
+restore_cache | output "$LOG_FILE"
+
+header "Installing binaries"
+install_bins | output "$LOG_FILE"
+
+build_dependencies() {
+  run_if_present 'heroku-prebuild'
+  if $PREBUILD; then
+    echo "Prebuild detected (node_modules already exists)"
+    rebuild_node_modules "$BUILD_DIR"
+  else
+    install_node_modules "$BUILD_DIR"
+  fi
+  run_if_present 'heroku-postbuild'
+}
+
+header "Building dependencies"
+build_dependencies | output "$LOG_FILE"
+
+cache_build() {
+  local cache_directories=$(get_cache_directories)
+
+  echo "Clearing previous node cache"
+  clear_cache
+  if ! ${NODE_MODULES_CACHE:-true}; then
+    echo "Skipping cache save (disabled by config)"
+  elif [ "$cache_directories" == "" ]; then
+    echo "Saving 2 cacheDirectories (default):"
+    save_cache_directories "$BUILD_DIR" "$CACHE_DIR" "$DEFAULT_CACHE"
+  else
+    echo "Saving $(echo $cache_directories | wc -w | xargs) cacheDirectories (package.json):"
+    save_cache_directories "$BUILD_DIR" "$CACHE_DIR" $cache_directories
+  fi
+  save_signature
+}
+
+header "Caching build"
+cache_build | output "$LOG_FILE"
+
+summarize_build() {
+  cd $BUILD_DIR
+  (npm ls --depth=0 | tail -n +2 || true) 2>/dev/null
+}
+
+header "Build succeeded!"
+summarize_build | output "$LOG_FILE"
+
+warn_no_start "$LOG_FILE"
+warn_unmet_dep "$LOG_FILE"
 
 export_env_dir $ENV_DIR
 
